[package]
name = "url-puller"
version = "0.1.0"
edition = "2021"

[dependencies]
simple_logger = "4.3.0"
log = "0.4.8"
tiny_http = "0.12.0"
serde_json = "1.0.114"
reqwest = { version = "0.11.25", features = ["blocking"] }
tl = "0.7.8"
